### ISSUE TITLE
Conflict with Angular Meteor 1.3+

### ISSUE THREAD

**Issue by jaysondaquer** [Urigo/angular-meteor-auth#27]
![image](https://cloud.githubusercontent.com/assets/7529733/17394261/bcb8aa98-5a5a-11e6-9612-e2872ba5b05b.png)

Following tutorial of the latest socially app (angular 1.5.x) and tried to add angular-meteor-auth package (depends on angular 1.4.x) 

Not sure what is the best way to resolve this. thanks!

**Comment by DAB0mB** [comment]
@jaysondaquer The use of Atmosphere package is deprecated, hence you should use

    $ npm install angular-meteor-auth --save

Rather than

    $ meteor add angular-meteor-auth

The main problem with using two separate package managers is that they are not correlated, so you will end up installing duplicate packages but from two different sources. After you install angular-meteor-auth, don't forget to import it and load it, like so:

```js
import 'angular-meteor-auth';

// ...

Angular.module(App, [
  'angular-meteor',
  'angular-meteor.auth'
]);
```

Hope it's clear now :-)
